### ISSUE TITLE
Errore sulla sezione Come testare in locale

### ISSUE THREAD

**Issue by corradopetrelli** [NandayDev/isda#3]
### Descrizione

Ho provato gli step descritti ma mi son bloccato allo step 5: 
```Lancia yarn prisma migrate dev per applicare le migrazioni al database.```

Questo è il log di errore:
```bash
yarn run v1.22.19
$ /Users/corrado/Documents/isda/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DIRECT_URL.
  -->  schema.prisma:8
   | 
 7 |   url       = env("DATABASE_URL")
 8 |   directUrl = env("DIRECT_URL")
   | 

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 5.3.1
```

### Possibili soluzioni

1. Installare `dotnet-cli`
2. Eseguire `dotenv -e .env.local -- yarn prisma migrate deploy`

oppure

1. Rinominare `.env.local` con `.env`
2. Aggiungere `.env` su `.gitignore`

Non conosco NextJS perciò potrei sbagliare io qualcosa ma con le due soluzioni sopra riportare tutti gli step vanno a buon fine.
Se vuoi apro una PR con una delle due soluzioni e modifico il README.md

**Comment by IgorZanellaDev** [comment]
Grazie per la segnalazione, fixato il README.md👍🏻
