### ISSUE TITLE
Errore dopo salvataggio voti negli input dei dati delle chat

### ISSUE THREAD

**Issue by IgorZanellaDev** [NandayDev/isda#4]
Nelle live, quando Giorgio salva i voti, rimangono dati "sporchi" negli input dei dati delle chat. Probabilmente é qualcosa dovuto al localstorage.

### Foto esempio
![image](https://github.com/NandayDev/isda/assets/10119449/14e33da2-1741-4d18-a9c0-af47c6d22c56)

**Comment by iamgiolaga** [comment]
Issue risolto [qua](https://github.com/NandayDev/isda/pull/7), credo possa essere chiuso
